### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by upgundecha** [superfly/docs#1257]
I was trying the basic example given on the sign-up page. It does not work and throws below error during lunch:

<img width="488" alt="image" src="https://github.com/superfly/docs/assets/1009929/d7c5639f-8dd6-47b0-83dd-d077267112d3">

What's `region maatate not found`? Is it `region mandate`?

**Comment by upgundecha** [comment]
This failed as well 
<img width="653" alt="image" src="https://github.com/superfly/docs/assets/1009929/fbc4c8e8-08b2-4bf7-a93a-091d0b789c96">

**Comment by andie787** [comment]
Thanks for submitting an issue. A few things were happening here, and they should be fixed now (or in the case of the error typo, soon). The problem was that `fly launch` was trying to create your app in the maa region, which is no longer available. Also, there was a typo in the error message, which should just read "region maa not found".

**Comment by upgundecha** [comment]
It may be worth adding this to your docs on how to start with a region

```
flyctl launch --region ams
```
